# Generated by Django 4.2 on 2023-04-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Special product',
                'verbose_name_plural': 'Special products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.product',),
        ),
    ]
